# Generated by Django 5.0.2 on 2024-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='price',
            field=models.IntegerField(),
        ),
    ]
