# Generated by Django 5.0.2 on 2024-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_total_price_alter_cartproducts_price'),
        ('main', '0002_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
